### PR TITLE
Feature/proto includes dont impose file structure 2016 03 13

### PR DESCRIPTION
**Pull request by sarietta**
Moves away from the dependence of api common on the google protobuf library itself. We were only relying on the `Empty` message, which was... empty so I just made the same message in `api_common` so we don't have to link against the protobuf library's implementation.

I also changed the imports of the protobufs to be relative paths, which will be much more portable as we move to new API libraries.

The rest of the files are just backups of the "release" version of the API currently in use.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/DotDashPay/ddp.api.common/pull/24" target="_blank">ReviewNinja

**Comment by cjrd** [comment]
LGTM

**Comment by cjrd** [comment]
Looks like this needs another merge since I just merged #23 into develop

**Comment by sarietta** [comment]
Should be GTG now.

**Pull request merged**
