### PR TITLE
Feature/example value injector 2016 03 16

### PR DESCRIPTION
**Pull request by sarietta**
This PR mostly implements a script that injects example values from the `spec/example-values.json` file into an autogenerated examples file (which is generated via the protobuf plugin for the respective language).

There is one other minor change which altered the API version number. That change was an update to a couple field names to make them consistent with other API requests/responses.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/DotDashPay/ddp.api.common/pull/23" target="_blank">ReviewNinja

**Comment by cjrd** [comment]
This looks good. Two questions:

(1) Should we regen the iOS api? Generally, when should we regen the APIs? Maybe when we merge to master?

(2) Does the example injector assume all message field names are unique? Is this a safe assumption?

**Comment by sarietta** [comment]
Good questions.

(1) It probably should be re-generated. I will add a todo for myself and take of that in the next day. More generally, anytime the API version number changes, all API libraries *should* be updated. In the future that rule needs to be more systematically enforced, but for now maybe we should just not pass a CR until it's satisfied.

(2) It does. I don't think that's a safe assumption in general, although it is kind of odd to have two example values defined (i.e. what's the use-case for this?). I can add an explicit check for that if you think it will save us headaches in the future.

**Comment by cjrd** [comment]
(1) Sounds good to me

(2) I could see multiple messages having the same field in the future, e.g. `info` is a pretty general field. We probably don't need to worry about this right now but perhaps create an issue so it won't get (too) lost.

**Pull request merged**
