### PR TITLE
Feature/documentation directly on responses 2016 02 19

### PR DESCRIPTION
**Pull request by sarietta**
This PR removes the response spec from the list of specification files since it was redundant given the protobuf files in `protobuf/impls`. One aspect of the PR that increased the changed line count is that I re-organized the files in `protobuf/impls` so that messages that define `responses` are grouped together and messages that define the arguments to `requests` are grouped separately.

The `api-spec` and the `request-spec` are still in this repo and may remain there depending on what we decide. The two options we have are:

1. Use the json spec files to define `requests` (current strategy)
2. Define requests directly in a `services.proto` that will live in `protobuf/impls`

As I was going through the exercise of potentially converting to option (2), I realized that the json format is actually a lot friendlier to work with, and since the `services.proto` can be auto-generated from the `api-spec` and the `request-spec`, using either method is exactly equivalent. There is no redundant work. Thus, I think we should continue to use the json approach, unless I am overlooking something. Let's chat offline @cjrd.

@muchable: You may want to look at this PR as well since you expressed interest in this aspect of the API.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/DotDashPay/ddp.api.common/pull/9" target="_blank">ReviewNinja

**Comment by cjrd** [comment]
Looks good; two questions:

1. I might have forgotten from a previous PR: but what's the difference between `/protobuf` and `/protobuf/impl`?
1. Should we have a CircleCI build that runs through all of the possible build commands / tests to verify that ddp.api.common is in a good state?

**Comment by sarietta** [comment]
`protobuf/impl` contains the human-written implementations of the protocol buffers needed by the API. These are messages that define the arguments to `requests` and the messages that refine the `responses`. 

The script `generate-protos.js` copies these into `protobuf` and generates the `services.proto` in `protobuf` as well, ensuring that before making that copy, the API version numbers have been set correctly and if not, the script copies the current contents of `protobuf` into `protobuf/versions/MAJOR.MINOR` first.

**Comment by sarietta** [comment]
I created an issue for 2.

**Pull request merged**
